### ISSUE TITLE
RouteValueDictionary Extension

### ISSUE THREAD

**Issue by waynebrantley** [ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers#13]
Several things we use want a RouteValueDictionary, so we need these additional extensions.
I could have added these extensions, but you made the RouteInformation class internal.  Any chance you could remove that modifier?

```
public static RouteValueDictionary RouteValueDictionary<TController>(
               this HtmlHelper helper,
               Expression<Func<TController, Task>> action,
               object routeValues = null)
           where TController : Controller
       {
           var routeInfo = RouteInformation.FromExpression<TController>(action, routeValues);
           return routeInfo.RouteValueDictionary;
       }
```

Thoughts?

**Comment by waynebrantley** [comment]
@ivaylokenov Thoughts?

**Comment by ivaylokenov** [comment]
@waynebrantley I am sorry, I have missed the e-mail from this issue. I am completely OK to remove the internal modifier so that you can extend the functionality. Will upload a new version in one to two days.

**Comment by ivaylokenov** [comment]
@waynebrantley Version 1.0.5 is now uploaded to NuGet. All internal classes are now public for better extensibility.
