### ISSUE TITLE
asp.net core

### ISSUE THREAD

**Issue by waynebrantley** [ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers#14]
Do you have the equivalent library for use in asp.net core?  (Full framework or a particular standard is fine)

**Comment by waynebrantley** [comment]
Think I have answered my own question.  You have this...essentially equivalent?
https://github.com/ivaylokenov/AspNet.Mvc.TypedRouting

**Comment by ivaylokenov** [comment]
@waynebrantley Yes, the AspNet.Mvc.TypedRouting library is equivalent and even has more features. If you believe it will do the job for you, may I close this issue?

**Comment by waynebrantley** [comment]
Yes, sounds great and thanks.
Did you make the internal classes public in that repo too?   That has worked well for us creating our own extensions for some additional points.   My plan is to eventually switch from this project to the core one to help us move!

**Comment by ivaylokenov** [comment]
@waynebrantley Some of the classes are internal but let me know which ones you need public and I will update the library! Just open an issue in the other repo.
