### ISSUE TITLE
Attribute Routing Area Not working

### ISSUE THREAD

**Issue by waynebrantley** [ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers#15]
https://github.com/ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers/blob/master/System.Web.Mvc.Expressions/Internals/MvcExtensions.cs#L44

At the line above, when your code tries to locate the RouteArea attribute, it incorrectly uses RoutePrefix.

The documentation for RoutePrefix says it defaults to the 'AreaName' and if that is blank it gets the area name from the namespace.  Nothing could be further from the truth!   The code is here:
http://sourcebrowser.io/Browse/ASP-NET-MVC/aspnetwebstack/src/System.Web.Mvc/RouteAreaAttribute.cs

As you can see, it does nothing.
The fix is easy...the line should be 
`` return routeAreaAttribute.AreaName;``

I just now encountered this as very few controllers we have use AttributeRouting.

**Comment by ivaylokenov** [comment]
@waynebrantley Thank you for the nice find. Would you like to open a pull request (I will add your name to the readme)? If not, I will fix it myself and upload a new version to Nuget.

**Comment by waynebrantley** [comment]
Done 
https://github.com/ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers/pull/16

**Comment by ivaylokenov** [comment]
@waynebrantley Thank you! Package is now uploaded to NuGet. I added your GitHub profile to the readme. 👍
