### ISSUE TITLE
can not support in razor?

### ISSUE THREAD

**Issue by JeffreyChan** [ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers#19]
i want to use it in CSHTML
something like:

` <li>@Html.ActionLink<HomeController>(c => c.Index(5))</li> `

**Comment by ivaylokenov** [comment]
Razor does not like generic, so you have to surround the call in brackets:

`<li>@(Html.ActionLink<HomeController>(c => c.Index(5)))</li>`

**Comment by JeffreyChan** [comment]
so I got it. thanks a lot. do you have any mvc pager library? do you recommend something?

**Comment by ivaylokenov** [comment]
@JeffreyChan You can use https://github.com/kpi-ua/X.PagedList for paging.

**Comment by JeffreyChan** [comment]
Thanks a lot.
