### ISSUE TITLE
Async actions

### ISSUE THREAD

**Issue by waynebrantley** [ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers#9]
```
public async Task<ActionResult> Index()
{ 
  if (await someAsyncCode())
     return this.RedirectToAction(c=>c.Index());   //<-- this says code needs to be awaited
  return View(); 
}
```
How do you handle async actions?
The above code gives compiler/editor warnings that the expression c->Index() needs awaited.
Of course awaiting it and making it async means your signaturres wont work.

**Comment by waynebrantley** [comment]
Potentially just need overloads for Task on all extensions?  (Can't easily try this as the code that is needed is marked internal)

```
public static RedirectToRouteResult RedirectToAction<TController>(this TController controller, Expression<Task<Action<TController>>> action, object routeValues = null) where TController : Controller

```

**Comment by ivaylokenov** [comment]
@waynebrantley We will add extensions allowing tasks in the next few days and upload a new version of the package. Thanks!

**Comment by waynebrantley** [comment]
That would be awesome, we cannot wait to use this.

**Comment by ivaylokenov** [comment]
@waynebrantley Async overloads are now implemented and packages are updated on NuGet.

**Comment by waynebrantley** [comment]
Awesome!
